version: '3'

services:
  db:
    container_name: pg_db
    image: postgres
    restart: unless-stopped
    networks:
      - local
    ports:
      - 5432:5432
    env_file:
      - 'config/.env.dev'

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    networks:
      - local
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  local:
    driver: bridge
