version: '3'

services:
  server:
    container_name: server
    restart: unless-stopped
    build: ./server
    volumes:
      - './server:/usr/src/server'
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
    networks:
      - local
      - public
    env_file:
      - 'config/.env.dev'

  db:
    container_name: pg_db
    image: postgres
    restart: unless-stopped
    networks:
      - local
    ports:
      - 5432:5432
    env_file:
      - 'config/.env.dev'

  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    volumes:
      - './frontend:/usr/src/frontend'
    ports:
      - '3000:3000'
    networks:
      - local
      - public
    env_file:
      - 'config/.env.dev'

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    networks:
      - local
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  local:
    driver: bridge
  public:
    driver: bridge
