version: '3'

services:
  server:
    container_name: server
    restart: unless-stopped
    build: ./server
    depends_on:
      - db
      - redis
    networks:
      - local
      - public
    env_file:
      - '.env'

  db:
    container_name: pg_db
    image: postgres
    restart: unless-stopped
    networks:
      - local
    ports:
      - 5432:5432
    env_file:
      - '.env'

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
    networks:
      - local
      - public
    env_file:
      - '.env'

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    networks:
      - local
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  local:
    driver: bridge
  public:
    driver: bridge
