version: '3'

services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=nodus
      - PGPASSWORD=pass
      - PGDATABASE=db_1
    links:
      - db
    volumes:
      - './server/src:/usr/src/server/src'
  db:
    container_name: pg_db
    image: postgres
    restart: always
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=nodus
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db_1
    volumes:
      - ./server/postgres-data:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend/src:/usr/src/frontend/src'
