version: '3'

services:
  server:
    environment:
      - CLIENT_URL=http://localhost:3000
    volumes:
      - './server:/usr/src/server'
    ports:
      - '5000:5000'

  frontend:
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
      - REACT_APP_SOCKET_BASE_URL=http://localhost:5000
      - REACT_APP_CLIENT_URL=http://localhost:3000
    volumes:
      - './frontend:/usr/src/frontend'
    ports:
      - '3000:3000'

  redis:
    ports:
      - "6379:6379"
