version: '3'

services:
  server:
    container_name: server
    restart: always
    build: ./server
    networks:
      - local
    ports:
      - '5000:5000'
    env_file:
      - '.env.docker'
    links:
      - db
      - redis
    volumes:
      - './server/src:/usr/src/server/src'

  db:
    container_name: pg_db
    image: postgres
    restart: always
    networks:
      - local
    ports:
      - '5432:5432'
    env_file:
      - '.env.docker'

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    networks:
      - local
    ports:
      - '3000:5000'
    expose:
      - '5000'
    env_file:
      - '.env.docker'
    volumes:
      - './frontend/src:/usr/src/frontend/src'

  redis:
    image: "redis:alpine"
    command: redis-server
    networks:
      - local
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master

  nginx:
    image: nginx:latest
    container_name: production_nginx
    depends_on:
      - db
      - redis
      - frontend
      - server
    networks:
      - local
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- '/etc/letsencrypt/:/etc/letsencrypt/'

networks:
  local:
    driver: bridge
  public:
    driver: bridge
