version: '3'

services:
  server:
    container_name: server
    restart: always
    build: ./server
    networks:
      - local
    ports:
      - '5000:5000'
    env_file:
      - '.env'
    links:
      - db
      - redis
    volumes:
      - './server/src:/usr/src/server/src'

  db:
    container_name: pg_db
    image: postgres
    restart: always
    networks:
      - local
    ports:
      - '5432:5432'
    env_file:
      - '.env'

  mobile:
    container_name: mobile
    restart: always
    build: ./mobile
    networks:
      - local
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    volumes:
      - './mobile/src:/usr/src/frontend/src'

  #log-client:
  #  container_name: log-client
  #  restart: always
  #  build: log-client
  #  networks:
  #    - local
  #  ports:
  #    - '3001:3001'
  #  expose:
  #    - '3001'
  #  env_file:
  #    - '.env'
  #  volumes:
  #    - './log-client/src:/usr/src/log-client/src'

  redis:
    image: "redis:alpine"
    command: redis-server
    networks:
      - local
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: production_nginx
    depends_on:
      - db
      - redis
      - mobile
      - server
    networks:
      - local
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./${NGINX_CONF_FILE}:/etc/nginx/nginx.conf

networks:
  local:
    driver: bridge
  public:
    driver: bridge
