global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "postgres-exporter"
    metrics_path: '/metrics'
    honor_labels: true
    scrape_interval: 30s
    scrape_timeout: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']