FROM node:14.16.1

WORKDIR /usr/src/server

COPY . .

## Install dependecies
RUN npm install

## build app when image is created.
RUN npm run build

## Copy hsb files
RUN cp -r ./src/admin/views ./build/src/admin/views

## run the node process
CMD ["npm", "run", "prod"]