#!/bin/bash

## Move to correct path (root of project)
cd ..
## pull latest frontend and server
docker pull ghcr.io/albinr99salt/no-name_server:$(git rev-parse --short HEAD)
docker pull ghcr.io/albinr99salt/no-name_frontend:$(git rev-parse --short HEAD)
docker-compose -f docker-compose.prod.yml up -d frontend server
docker exec server sh -c "npm run migrate:latest"