#!/bin/bash

## Rebuild containers
cd ..
docker-compose build server frontend
## Restart containers
docker-compose restart server frontend
## Run migration in new container
docker exec server sh -c "npm run migrate:latest"
