name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Frontend Docker image
      run: |
        docker build ./frontend/Dockerfile.prod -t no-name/frontend:latest
    - name: Build Server Docker image
      run: |
        docker build ./server/Dockerfile.prod -t no-name/frontend:latest
