name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare env
      run: |
        cp ./config/.env.docker .env
        set -o allexport; cat .env | grep "^REACT_APP_*" > .env.tmp; source .env.tmp; set +o allexport; rm -rf .env.tmp;
    - name: Build Docker images
      run: |
        make prod-build
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build image and push to GitHub Container Registry
      run: |
        docker tag no-name_frontend ghcr.io/albinr99salt/no-name_frontend:latest
        docker tag no-name_server ghcr.io/albinr99salt/no-name_server:latest
        docker push ghcr.io/albinr99salt/no-name_frontend
        docker push ghcr.io/albinr99salt/no-name_frontend
