name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_IMAGE: ghcr.io/albin-rohde/no-name_app
    steps:
    - name: check out code
      uses: actions/checkout@v2

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest


    - name: Pull images
      run: |
        docker pull ${APP_IMAGE}:latest

    - name: Build and Push app
      run: |
        docker buildx build \
        -t ${APP_IMAGE}:${GITHUB_SHA::7} \
        -t ${APP_IMAGE}:latest \
        -f ./Dockerfile \
        --cache-from ${APP_IMAGE}:latest \
        --platform=linux/amd64 \
        --output type=image,push=true \
        ./
