name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FRONTEND_IMAGE: ghcr.io/albinr99salt/no-name_frontend
      BACKEND_IMAGE: ghcr.io/albinr99salt/no-name_server
    steps:
    - name: check out code
      uses: actions/checkout@v2

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest


    - name: Pull images
      run: |
        docker pull ${FRONTEND_IMAGE}:latest
        docker pull ${BACKEND_IMAGE}:latest

    - name: Build and Push frontend
      run: |
        docker buildx build \
        -t ${FRONTEND_IMAGE}:${GITHUB_SHA::7} \
        -t ${FRONTEND_IMAGE}:latest \
        -f ./frontend/Dockerfile.prod \
        --cache-from ${FRONTEND_IMAGE}:latest \
        --build-arg REACT_APP_API_BASE_URL=https://api.fasoner.party \
        --build-arg REACT_APP_SOCKET_BASE_URL=https://api.fasoner.party \
        --build-arg REACT_APP_CLIENT_URL=https://fasoner.party \
        --platform=linux/amd64 \
        --output type=image,push=true \
        ./frontend

    - name: Build and Push server
      run: |
        docker buildx build \
        -t ${BACKEND_IMAGE}:${GITHUB_SHA::7} \
        -t ${BACKEND_IMAGE}:latest \
        -f ./server/Dockerfile.prod \
        --cache-from ${BACKEND_IMAGE}:latest \
        --platform=linux/amd64 \
        --output type=image,push=true \
        ./server
