name: Build and Publish Docker Image

on:
  push:
    branches:
      - '*'

env:
  APP_IMAGE: ghcr.io/albin-rohde/no-name_app

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Get short SHA
        id: short-sha
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA::7})"

      - name: Build and push Docker image (master branch)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.APP_IMAGE }}:latest, ${{ env.APP_IMAGE }}:${{ steps.short-sha.outputs.sha }}

      - name: Build and push Docker image (stage branch)
        if: github.ref == 'refs/heads/stage'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.APP_IMAGE }}:stage, ${{ env.APP_IMAGE }}:${{ steps.short-sha.outputs.sha }}

      - name: Build and push Docker image (other branches)
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/stage'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.APP_IMAGE }}:${{ steps.short-sha.outputs.sha }}
